start cmd /k "mongod --dbpath c:\mongo\db"
start cmd /k "mongo"
start cmd /k "d: & cd d:\yandexdisk\sketchbook & webpack"
start cmd /k "d: & cd d:\yandexdisk\sketchbook & supervisor --watch app.js app.js"
start cmd /k "d: & cd d:\yandexdisk\sketchbook"
